{
 "title": "VMware ESXi",
 "description": "VMware ESXi single instance graphs.",
 "tags": [
  "prometheus",
  "vmware",
  "esxi"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "esxhost",
    "label": "esxhost",
    "query": {
     "query": "label_values(vmware_host_boot_timestamp_seconds,host_name)"
    }
   },
   { "name": "datastore", "query": { "query": "vmware_datastore_capacity_size" } }
  ]
 },
 "panels": [
  {
   "title": "ESXi host uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - vmware_host_boot_timestamp_seconds{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Host Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg((vmware_host_memory_usage{host_name=~\"$esxhost\"}) * 100 / (vmware_host_memory_max{host_name=~\"$esxhost\"}))"
    }
   ]
  },
  {
   "title": "Host CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg((vmware_host_cpu_usage{host_name=~\"$esxhost\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$esxhost\"}))"
    }
   ]
  },
  {
   "title": "Host Memory ",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_host_memory_max{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Host Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_host_memory_usage{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Host Memory Free",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_host_memory_max{host_name=~\"$esxhost\"} - vmware_host_memory_usage{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "DS $datastore usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "repeat": "datastore",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - vmware_datastore_freespace_size{ds_name=~\"$datastore\"} / vmware_datastore_capacity_size{ds_name=~\"$datastore\"}"
    }
   ]
  },
  {
   "title": "DS $datastore usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - vmware_datastore_freespace_size{ds_name=~\"$datastore\"} / vmware_datastore_capacity_size{ds_name=~\"$datastore\"}"
    }
   ]
  },
  {
   "title": "Number of VMs",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vmware_vm_power_state{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Number of active VMs",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vmware_vm_power_state{host_name=~\"$esxhost\"} == 1) "
    }
   ]
  },
  {
   "title": "Number of powered off VMs",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vmware_vm_power_state{host_name=~\"$esxhost\"} == 0)"
    }
   ]
  },
  {
   "title": "List of powered off VMs",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 15 },
   "targets": [
    {
     "expr": "vmware_vm_power_state{host_name=~\"$esxhost\"} == 0",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  },
  {
   "title": "vm Memory Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_mem_active_average{host_name=~\"$esxhost\"}",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  },
  {
   "title": "vm CPU usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_usage_average{host_name=~\"$esxhost\"}",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  },
  {
   "title": "VM unused memory ",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(30,(vmware_vm_memory_max{host_name=~\"$esxhost\"} - (vmware_vm_mem_active_average{host_name=~\"$esxhost\"} / 1024)))",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  },
  {
   "title": "VM unused memory  (%)",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(30,(1 - (vmware_vm_mem_active_average{host_name=~\"$esxhost\"} / 1024) / vmware_vm_memory_max{host_name=~\"$esxhost\"}))",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  }
 ]
}